import { ProtocolScene } from "./types";

export const SCENES: ProtocolScene[] = [
  {
    id: "foundation",
    title: "1. Algebraic Foundation",
    shortExplanation: "The protocol operates in high-dimensional lattice spaces. We represent the public matrix $\\mathbf{A}$ as the underlying grid that defines our coordinate system.",
    cameraPose: { position: [10, 6, 10], target: [0, 0, 0] },
    visibleObjects: ["lattice", "axes", "basis-a"],
    actorFocus: null,
    equationOverlay: "\\begin{aligned} \\mathbf{A} &\\leftarrow \\mathcal{R}_q^{k \\times k} \\\\ &\\text{(Publicly Known Matrix)} \\end{aligned}",
  },
  {
    id: "secret-gen",
    title: "2. Key Generation: Secrets",
    shortExplanation: "Bob generates a secret vector $\\mathbf{s}$ and a small error vector $\\mathbf{e}$. These are kept private and form the basis of his security.",
    cameraPose: { position: [6, 4, 6], target: [1, 1, 1] },
    visibleObjects: ["lattice", "axes", "basis-a", "secret-point", "noise-cloud"],
    actorFocus: "B",
    equationOverlay: "\\begin{aligned} \\mathbf{s}, \\mathbf{e} &\\leftarrow \\text{Small Random Vectors} \\\\ &\\text{(Bob's Private Keys)} \\end{aligned}",
  },
  {
    id: "keygen",
    title: "3. Key Generation: Public Key",
    shortExplanation: "Bob computes his public key $\\mathbf{b} = \\mathbf{As} + \\mathbf{e}$. The error $\\mathbf{e}$ 'smudges' the result, making it a Learning With Errors (LWE) instance.",
    cameraPose: { position: [8, 5, 8], target: [1, 1, 0.5] },
    visibleObjects: ["lattice", "axes", "basis-a", "basis-b", "secret-point", "noise-cloud"],
    actorFocus: "B",
    equationOverlay: "\\mathbf{b} = \\mathbf{A}\\mathbf{s} + \\mathbf{e}",
  },
  {
    id: "encapsulation",
    title: "4. Encapsulation (Alice)",
    shortExplanation: "Alice uses Bob's public key $\\mathbf{b}$ and matrix $\\mathbf{A}$ to encrypt a message. She adds her own noise to ensure the ciphertext is secure.",
    cameraPose: { position: [8, 5, 8], target: [-1, 0.5, 1.5] },
    visibleObjects: ["lattice", "axes", "basis-a", "basis-b", "u-vector", "v-vector", "r-vector", "e1-noise", "e2-noise"],
    actorFocus: "A",
    equationOverlay: "\\begin{aligned} \\mathbf{u} &= \\mathbf{A}^T\\mathbf{r} + \\mathbf{e}_1 \\\\ \\mathbf{v} &= \\mathbf{b}^T\\mathbf{r} + \\mathbf{e}_2 + \\text{m} \\end{aligned}",
  },
  {
    id: "decapsulation",
    title: "5. Decapsulation (Bob)",
    shortExplanation: "Bob uses his secret $\\mathbf{s}$ to 'undo' the matrix transformation. Because $\\mathbf{e}$ is small, he can round the result to recover the original message.",
    cameraPose: { position: [5, 3, 5], target: [0, 2, 0] },
    visibleObjects: ["lattice", "axes", "basis-a", "basis-b", "u-vector", "v-vector", "secret-point", "shared-secret-point"],
    actorFocus: "B",
    equationOverlay: "m \\approx \\mathbf{v} - \\mathbf{s}^T\\mathbf{u}",
  },
  {
    id: "brute-force",
    title: "6. Brute Force Attempt (Eve)",
    shortExplanation: "An attacker (Eve) tries to guess $\\mathbf{s}$. Even in this simplified 3D view, there are thousands of possibilities. In 256 dimensions, it is impossible.",
    cameraPose: { position: [12, 8, 12], target: [0, 0, 0] },
    visibleObjects: ["lattice", "axes", "basis-a", "basis-b", "brute-force-points"],
    actorFocus: "C",
    equationOverlay: "\\text{Find } \\mathbf{s}' \\text{ s.t. } ||\\mathbf{As}' - \\mathbf{b}|| \\text{ is small}",
  },
  {
    id: "security",
    title: "7. Security Guarantee",
    shortExplanation: "The security relies on the Shortest Vector Problem (SVP). Finding the secret vector in a 'smudged' lattice is computationally infeasible for quantum computers.",
    cameraPose: { position: [16, 10, 16], target: [0, 0, 0] },
    visibleObjects: ["lattice", "axes", "basis-a", "basis-b", "ambiguity-sphere"],
    actorFocus: "C",
    equationOverlay: "\\begin{aligned} \\text{Classical Complexity: } & 2^{192} \\\\ \\text{Quantum Complexity: } & 2^{160} \\end{aligned}",
  }
];
